### ISSUE TITLE
Can't find libmediainfo

### ISSUE THREAD

**Issue by the-real-wizhack** [romancin/tinymediamanager-docker#28]
It's appear that the libmediainfo is not found on my systems.
Debian 9 x64
Docker manager throught openmediavault

`
2020-04-01 12:37:45,867 ERROR [main] o.t.thirdparty.MediaInfoUtils:108 - could not load MediaInfo!
2020-04-01 12:37:45,868 ERROR [main] o.t.thirdparty.MediaInfoUtils:110 - Please try do install the library from your distribution
2020-04-01 12:37:46,647 ERROR [main] org.tinymediamanager.core.TmmDateFormat:126 - could not load JNA: Could not initialize class com.sun.jn$
2020-04-01 12:37:48,233 ERROR [main] o.tinymediamanager.thirdparty.MediaInfo:630 - Failed to load mediainfo
`
What can i do to tell the image where is my libmediainfo.
` /usr/lib/x86_64-linux-gnu/libmediainfo.so.0
/usr/lib/x86_64-linux-gnu/libmediainfo.so
/usr/lib/x86_64-linux-gnu/libmediainfo.so.0.0.0
`

**Comment by gitthangbaby** [comment]
in my case, can't find this one, never processed files (the users root,app,deamon,nginx can read/write the files on terminal):
```
ERROR org.tinymediamanager.ui.TmmUIHelper - could not call nfd - /config/native/linux-x64/liblwjgl_nfd.so.0: cannot open shared object file: No such file or directory
ERROR o.t.core.movie.tasks.MovieUpdateDatasourceTask - error on listFilesAndDirs /media/Movies
```

**Comment by francis-xjl** [comment]
I have same problem:
`2020-05-13 08:15:56,699 INFO  [main] org.tinymediamanager.TinyMediaManager:219 - starting tinyMediaManager
2020-05-13 08:15:56,743 ERROR [main] o.tinymediamanager.thirdparty.MediaInfo:630 - Failed to load mediainfo
java.lang.UnsatisfiedLinkError: /config/xdg/cache/JNA/temp/jna5592623854120369877.tmp: /config/xdg/cache/JNA/temp/jna5592623854120369877.tmp: failed to map segment from shared object
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at org.tinymediamanager.thirdparty.MediaInfoLibrary.<clinit>(MediaInfoLibrary.java:37)
	at org.tinymediamanager.thirdparty.MediaInfo.staticOption(MediaInfo.java:626)
	at org.tinymediamanager.thirdparty.MediaInfo.staticOption(MediaInfo.java:612)
	at org.tinymediamanager.thirdparty.MediaInfo.version(MediaInfo.java:574)
	at org.tinymediamanager.thirdparty.MediaInfoUtils.loadMediaInfo(MediaInfoUtils.java:83)
	at org.tinymediamanager.TinyMediaManager$1.run(TinyMediaManager.java:244)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2020-05-13 08:15:56,744 ERROR [main] o.t.thirdparty.MediaInfoUtils:89 - could not load MediaInfo!
2020-05-13 08:15:56,744 ERROR [main] o.t.thirdparty.MediaInfoUtils:91 - Please try do install the library from your distribution
2020-05-13 08:15:56,985 INFO  [main] o.tinymediamanager.core.movie.MovieList:368 - found 0 movies in database
2020-05-13 08:15:56,990 INFO  [main] o.tinymediamanager.core.movie.MovieList:389 - found 0 movieSets in database
2020-05-13 08:15:57,100 INFO  [main] o.t.core.tvshow.TvShowList:360 - found 0 TV shows in database
2020-05-13 08:15:57,101 INFO  [main] o.t.core.tvshow.TvShowList:417 - found 0 episodes in database
2020-05-13 08:15:57,884 ERROR [main] org.tinymediamanager.core.TmmDateFormat:126 - could not load JNA: Could not initialize class com.sun.jna.Native
2020-05-13 08:16:00,469 ERROR [main] o.tinymediamanager.thirdparty.MediaInfo:630 - Failed to load mediainfo
java.lang.NoClassDefFoundError: Could not initialize class org.tinymediamanager.thirdparty.MediaInfoLibrary
	at org.tinymediamanager.thirdparty.MediaInfo.staticOption(MediaInfo.java:626)
	at org.tinymediamanager.thirdparty.MediaInfo.staticOption(MediaInfo.java:612)
	at org.tinymediamanager.thirdparty.MediaInfo.version(MediaInfo.java:574)
	at org.tinymediamanager.ui.MainWindow.initialize(MainWindow.java:264)
	at org.tinymediamanager.ui.MainWindow.<init>(MainWindow.java:105)
	at org.tinymediamanager.TinyMediaManager$1.run(TinyMediaManager.java:308)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by halvliter** [comment]
Just installed this on OpenMediaVault using portainer, and got the same error. Does it still work ?

**Comment by Ano10** [comment]
I have the same issue. Any news about it ?
How can I help ?

**Comment by Ano10** [comment]
I have MediaInfo working now.

Short version: The filesystem of your drive where `/config` belong must support execute permissions on files.
In fstab you have to check if your filesystem mount option doesn't have `noexec` or `user` option.

if you need to ad `exec` option, it as to be after `user` option if present in you mount options. `user` option implies `noexec, nosuid, nodev`.

Long version: My `/config` folder is on a different drive than my system and by default this drive filesystem have `noexec` option. Recently I've install ESPhome docker and I have issue compiling. I've find the solution on [ESPHome github](https://github.com/esphome/issues/issues/2817). I wondered if this was also preventing MediaInfo to work. After modifiying filesystem mount option MediaInfo is now working.
