### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Sirfrancis18** [romancin/tinymediamanager-docker#39]
my library is quite big and now tmm doesn't work anymore. when starting the docker it shows the following error
`java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
	at com.sun.nio.zipfs.ZipFileSystem$EntryOutputStream.write(ZipFileSystem.java:1579)
	at java.nio.file.Files.copy(Files.java:2909)
	at java.nio.file.Files.copy(Files.java:3027)
	at java.nio.file.CopyMoveHelper.copyToForeignTarget(CopyMoveHelper.java:126)
	at java.nio.file.Files.copy(Files.java:1277)
	at org.tinymediamanager.core.Utils.lambda$createZip$1(Utils.java:1445)
	at org.tinymediamanager.core.Utils$$Lambda$22/1480476051.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.tinymediamanager.core.Utils.createZip(Utils.java:1434)
	at org.tinymediamanager.core.Utils.createBackupFile(Utils.java:1158)
	at org.tinymediamanager.core.Utils.createBackupFile(Utils.java:1134)
	at org.tinymediamanager.TinyMediaManager$1.doStartupTasks(TinyMediaManager.java:450)
	at org.tinymediamanager.TinyMediaManager$1.run(TinyMediaManager.java:183)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)`

**Comment by EZarnosky** [comment]
I ran into the same issue with mine. I found the following [page](https://www.tinymediamanager.org/help/faq#java-heap-space-errors). Read the v3 section. Creating the extra.txt file worked for me. depending on the size of your library you might need to increase the memory size (their example shows 1gb - 1024m).

Hope that helps you.
